config/routes.rb
Rails.application.routes.draw do
root 'home#index'
get 'index/home', to: 'home#index'
get 'about/home', to: 'home#about'
get 'posts', to: 'posts#index'
get '/new/posts', to: 'posts#new'
get '/show/posts', to: 'posts#show'
get '/intervision/posts', to: 'posts#intervision'
get '/mazer/posts', to: 'posts#mazer'
get '/quantum/posts', to: 'posts#quantum'

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_model!


  protected

  def after_sign_in_path_for(resource)
        root_path(current_model)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_model!
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_model!
  def index
  	@posts = Post.all
    if params[:search]
      @posts = post.search(params[:search])
    else
      @posts = Post.all
    end
  end

  def show
  end

  # def new
  # 	@posts = post.new
  # end

  def create
  	@post = post.new(post_params)
    @post.models_id = current_model.id
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render :new
    end
  end

  def edit
  end

  def update
  	if @post.update(post_params)
  		redirect_to post_path(@post)
  	else
  		render :edit
    end
  end

  def destroy
  	@post.destroy
  	redirect_to post_path
  end

  private


  	def find_post
  		@post = Post.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<%= image_tag("logo.jpeg", :alt => "rss feed", :height =>"100", :width => "220", :align=> "left") %>
<ul class="dropdown-menu">
  <li><%= link_to 'Overview', posts_path %></li>
</ul>
<ul class="nav navbar-nav navbar-center">
  <li><%= link_to 'Home', index_home_path %></li>
  <li><%= link_to 'Managers', about_home_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portfolio<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Overview', posts_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to 'Alipine Air express', posts_path %></li>
      <li><%= link_to 'Geopower', new_posts_path %></li>
      <li><%= link_to 'Intellibed', show_posts_path %></li>
      <li><%= link_to 'Intervision System Technology', intervision_posts_path %></li>
      <li><%= link_to 'Mazer Encryption', mazer_posts_path %></li>
      <li><%= link_to 'Quantum IR Technologies', quantum_posts_path %></li>
    </ul>
  </li>
</ul>
</div>
</div>
</nav>
<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
  <%= image_tag("man.jpeg", :alt => "rss feed", :height =>"100%", :width => "100%") %>
</div>

<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2>Greg Robinson</h2>
        <h3>Founder/Managing Partner</h3>
        <p>Greg has over 30 years of business experience as a management consultant, entrepreneur, investment advisor, and private equity investor. </p>
        <p>As a management consultant at Bain & Company, McKinsey & Company, Price Waterhouse and EHS Partners, he advised corporate clients on matters of strategic and operational significance to improve business performance and profitability. Working directly with CEOs, he helped develop and implement discrete revenue and cost initiatives that substantially increased sustainable earnings.</p>
        <p>As a pre- and post-IPO executive at Staples, and in other entrepreneurial endeavors, he helped launch and lead companies in health care, education, business services, energy, and entertainment. </p>
        <%= image_tag("Greg.jpeg", :alt => "rss feed", :height =>"300", :width => "320", :align=> "right") %>
        <p>As a wealth advisor at Wells Fargo Private Bank, he helped family offices and other large clients deploy and diversify their investments. As a managing director at The CAPROCK Group, a multi-family office, he founded and led the Park City office and helped double the firm's assets under management to $3 billion.</p>
        <p>Greg co-founded RLG Capital in November 2013, where he and Mark Lisonbee have invested in six portfolio companies. He currently serves on the boards of Mazer Encryption, Geopower Energy, Quantum IR Technologies, and InterVision Systems Technologies. </p>
        <p>Greg has served in numerous church, civic, community and non-profit capacities. He was a National Finance Committee member for Romney For President (2008, 2012) and a Utah state delegate at the 2012 GOP Convention. He currently serves on the executive committee of the BYU Broadcasting Leadership Council and on the Advisory Boards of Progress Through Business and the Ethics Initiative at BYU's Wheatley Institution.</p>
        <p>Greg earned a BA in English and French from Brigham Young University and an MBA from Harvard University, where he was a LeBaron-McArthur-Ellis Fellow. Married for 33 years, he and his wife Robin are the parents of four grown children.</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2>MARK W. LISONBEE</h2>
        <h3>Founder/Managing Partner</h3>
        <p>During his 30+ year career, Mark has distinguished himself for his expertise in sourcing and executing growth equity and buyout deals.</p>
        <p>As an entrepreneur and business owner, he co-founded and helped grow over a dozen startup companies. Six of them resulted in successful exits. His two most recent companies were acquired by Nutraceutical Corp, where he then worked as a marketing and business development executive helping negotiate and close the acquisitions of over twenty public and private companies.</p>
        <p>Mark has been a leading figure in the natural products industry his entire career, with experience at the venture, growth, and buyout stages helping oversee profit and loss statements, product formulation, manufacturing, publishing, branding, and distribution. /p>
          <%= image_tag("Mark.jpeg", :alt => "rss feed", :height =>"300", :width => "320", :align=> "right") %>
        <p>As a management consultant, he helped United Airlines, Safeway, E-trade, Nutraceutical Corp, and others develop and implement customer loyalty programs. Mark's work at United Airlines helped revolutionize the frequent flyer industry by providing customers the opportunity to buy miles directly from the airline in order to qualify for award tickets.</p>
        <p>Mark co-founded RLG Capital in November 2013, where he and Greg Robinson have invested in six portfolio companies to date. He currently serves on the boards of Mazer Encryption and Quantum IR Technologies. </p>
        <p>Throughout Mark's professional career, he has served in church, community and non-profit capacities. He currently serves on the BYU Broadcasting Leadership Council.</p>
        <p>Mark studied business management and marketing at Brigham Young University. Married for 33 years, he and his wife Terri have three grown children and one grandchild.</p>
    </div>
</div>

app/views/home/index.html.erb
       <!-- adding a fixed makes the video follow in content -->
   <div style="position: absolute; z-index: -99; width: 100%; height: 100%">
     <iframe width="100%" height="560"  src="//www.youtube.com/embed/x3eIKSXXncc?rel=0&autoplay=1"frameborder="0" allowfullscreen></iframe>
          <nav class="navbar navbar-default, style="color: #F4F0F7" ">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

                <!-- <a class="navbar-brand" href="#">Brand</a> -->
               </div>
              </div>
            </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <!-- <ul class="nav navbar-nav">
                  <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                  <li><a href="#">Link</a></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="#">One more separated link</a></li>
                    </ul>
                  </li>
                </ul> -->
                <!-- <form class="navbar-form navbar-left">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form> -->
                <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Approach<span class="caret"></span></a> -->
                <%= image_tag("logo.jpeg", :alt => "rss feed", :height =>"100", :width => "220", :align=> "left") %>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Overview', posts_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="#">Home</a></li>
                  <li><%= link_to 'Managers', about_home_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portfolio<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Overview', posts_path %></li>
                      <li role="separator" class="divider"></li>
                      <li><%= link_to 'Alipine Air express', posts_path %></li>
                      <li><%= link_to 'Geopower', new_posts_path %></li>
                      <li><%= link_to 'Intellibed', show_posts_path %></li>
                      <li><%= link_to 'Intervision System Technology', intervision_posts_path %></li>
                      <li><%= link_to 'Mazer Encryption', mazer_posts_path %></li>
                      <li><%= link_to 'Quantum IR Technologies', quantum_posts_path %></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    <!-- <script>
    $(document).ready(function(){
    $('.carousel-content').slick();
      prevArrow:"<img class='a-left control-c prev slick-prev' src='../images/shoe_story/arrow-left.png'>",
      nextArrow:"<img class='a-right control-c next slick-next' src='../images/shoe_story/arrow-right.png'>"
      });
   </script> -->
   <li style="padding-top: 460px"></li>
   <a href="#about">
       <%= image_tag("arrow.jpeg", :alt => "rss feed", :height =>"30", :width => "80" ) %>
       <i class="fa fa-angle-double-down animated"></i>
   </a>
<li style="padding-top: 0px"></li>
<script>
$(window).scroll(collapseNavbar);
$(document).ready(collapseNavbar);

// jQuery for page scrolling feature - requires jQuery Easing plugin
$(function() {
    $('a.page-scroll').bind('click', function(event) {
        var $anchor = $(this);
        $('html, body').stop().animate({
            scrollTop: $($anchor.attr('href')).offset().top
        }, 1500, 'easeInOutExpo');
        event.preventDefault();
    });
});
$('.navbar-collapse ul li a').click(function() {
    $(this).closest('.collapse').collapse('toggle');
});
</script>



<!-- <header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2"> -->
                    <!-- <h1 class="brand-heading">Grayscale</h1>
                    <p class="intro-text">A free, responsive, one page Bootstrap theme.
                        <br>Created by Start Bootstrap.</p> -->

                    <!-- <a href="#about" class="btn btn-circle page-scroll">
                        <%= image_tag("arrow.jpeg", :align=> "right", :alt => "rss feed", :height =>"30", :width => "80" ) %>
                        <i class="fa fa-angle-double-down animated"></i>
                    </a> -->
                <!-- </div>
            </div>
        </div>
    </div>
</header> -->


<h2 style="padding-top: 100px;">Helping Disruptive Innovators Succeed.
Helping Disruptive Innovators Succeed.</h2>
<p style="padding-top: 30px;">At RLG Capital, a Park City based private investment firm, we help disruptive innovators find the resources necessary to succeed.</p>

<p>We acquire a controlling interest in privately held companies and bring the capital and leadership necessary to accelerate growth and profitability. We originate the deal, engage the right operating experts, secure the remaining capital, and work closely with our co-investors and with management to enhance enterprise value and achieve compelling returns.</p>

<p style="padding-bottom: 200px;">We are an independent private equity sponsor with operating experience and access to capital through family offices and institutional investors. We believe our hands-on, collaborative sponsorship brings a new and needed approach to venture capital and private equity investing.</p>


  <%= image_tag("manager.jpeg", :alt => "rss feed", :height =>"80", :width => "300" ) %>
<script>
$('#myCollapsible').on('hidden.bs.collapse', function () {
})
</script>

<section id="" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>INVESTMENT CRITERIA</h2>
            <p>Characteristics. We look for companies with proven business models, strong market potential, sustainable competitive advantages, and products or services that are disruptive to their industry -- companies that solve problems and satisfy demand through superior innovation, creativity, economics and execution. </p>
            <p>Size. We look for companies with EBITDA of $5-15 million or with an enterprise value of $20 to $100 million.</p>
            <p>Sectors. We invest in the sectors where our team has deep experience and has previously invested with success. Those sectors include aerospace, business services, consumer products, education, energy, entertainment, health, media, technology, and transportation.</p>
            <p>Location. We look for companies with a connection to Utah and the Mountain West, though we invest wherever we find the best opportunities.</p>
            <p>Amount. We look to invest a minimum of $5mm for a controlling interest in the voting shares of the company.</p>
            <p>Tenure. We typically hold our investments for a minimum of three years, actively working with management to execute our growth strategy until we accomplish a successful exit.</p>
            <p>Returns. We look for investments that we believe can reasonably achieve a minimum IRR of 25%.</p>
        </div>
    </div>
</section>

<section id="about" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>WHAT WE LOOK FOR</h2>
            <p>At RLG Capital, we look for companies with proven business models, strong market potential, and sustainable competitive advantages. Once we find them, we believe that smart, properly structured Reinvestment capital + experienced, properly focused Leadership = business Growth and profitability.</p>
            <p>We are private equity sponsor with access to billions in investment capital through our proprietary relationships with family offices, multi-family office firms, and investment funds.</p>
        </div>
    </div>
</section>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="padding-bottom: 100px;" "margin-top: 50px;">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active" alt="...">
      <%= image_tag "alpine.jpeg", class: 'responsive-img rounded-border' %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item" alt="...">
      <%= image_tag "geopower.jpeg", class: 'responsive-img rounded-border' %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <%= image_tag "intellibed.jpeg", class: 'responsive-img rounded-border' %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <%= image_tag "mazer.jpeg", class: 'responsive-img rounded-border' %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <%= image_tag "quantum.jpeg", class: 'responsive-img rounded-border' %>
      <div class="carousel-caption">
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <%= image_tag("logo.jpeg", :alt => "rss feed", :height =>"50", :width => "0", :align=> "left") %>
    <ol class="breadcrumb">
     <li><a href="#">Home</a></li>
     <li><a href="#">About Us</a></li>
     <li><a href="#">Contact Us</li>
</ol>


  </div>
</nav>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <li><%= link_to 'Rlg Capital', root_path %></li>
    <!-- <li><%= link_to 'blah', new_post_path %></li> -->
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rlgcapital</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Our CNC Manines</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/intervision.html.erb
<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
  <iframe frameborder="0" height="100%" width="100%"
    src="https://youtube.com/embed/0wCC3aLXdOw?autoplay=1&controls=0&showinfo=0&autohide=1">
  </iframe>
</div>
<h1>InterVision Systems Technologies</h1>

<blockquote cite="http://www.worldwildlife.org/who/index.html">
For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.
</blockquote>







<h3>Overview </h3>
<section id="about" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>INVESTMENT CRITERIA</h2>
            <p> </p>
            <p>
        </div>
    </div>
</section>

app/views/posts/mazer.html.erb
<h1>hi</h1>

app/views/posts/new.html.erb
<h1>hahaahh</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/quantum.html.erb
<h1>hello there</h1>

app/views/posts/show.html.erb
<h1>Our work</h1>
<%= link_to 'Post', posts_path, class: 'btn-small #eeeeee grey lighten-3' %>